name: CI/CD to deploy on EKS

on:
  push:
    branches:
      - main
    paths:
      - "app/**"
      - "helm/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
      DOCKER_REPO: ${{ secrets.DOCKER_REPO }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Check if EKS cluster exists
        id: check_cluster
        run: |
          if aws eks describe-cluster --name $CLUSTER_NAME --region $AWS_REGION > /dev/null 2>&1; then
            echo "cluster_exists=true" >> $GITHUB_ENV
          else
            echo "cluster_exists=false" >> $GITHUB_ENV
            echo "Cluster not found. Skipping deployment."
            exit 0
          fi

      - name: Login to registry
        if: env.cluster_exists == 'true'
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Set Short SHA
        run: echo "IMAGE_TAG=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        if: env.cluster_exists == 'true'
        env:
          DOCKER_REPO: ${{secrets.DOCKER_REPO}}
        run: |
          docker build -t $DOCKER_REPO:${{ env.IMAGE_TAG }} -f app/Dockerfile .
          docker push $DOCKER_REPO:${{ env.IMAGE_TAG }}

      - name: Update kubeconfig
        if: env.cluster_exists == 'true'
        run: |
          aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION

      - name: Install Helm
        if: env.cluster_exists == 'true'
        run: |
            curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
            
      - name: Deploy with Helm
        if: env.cluster_exists == 'true'
        run: |
          CURRENT_HOST=$(kubectl get ingress app-helm -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' || echo "")

          helm upgrade --install app ./helm \
            --set ingress.enabled=true \
            --set image.repository=$DOCKER_REPO \
            --set image.tag=${{ env.IMAGE_TAG }} \
            --set ingress.hosts[0].host="$CURRENT_HOST" \
            --set ingress.tls[0].hosts[0]="$CURRENT_HOST" \
            --set ingress.hosts[0].paths[0].path="/" \
            --set ingress.hosts[0].paths[0].pathType=Prefix \
            --set ingress.tls[0].secretName=app-tls
            
      - name: Skip if cluster not available
        if: env.cluster_exists == 'false'
        run: echo "EKS cluster not found. Skipping deployment."